# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wOgHLRY8LrZEWb_nbnTk_dxH20WzTJh
"""

#1
String = "Are you there yet"
vowel = "AEIOUaeiou"
Total = sum(1 for char in String if char in vowel)
print("vowel count is :", Total)

#2
def count_vowels(s):
    vowels = "aeiou"
    result = {}

    for v in vowels:
        count = 0

        for ch in s:
            if ch == v:
                count = count + 1

        result[v] = count

    return result


s = input("Enter a string: ")
print(count_vowels(s))

#3
N = int(input(""))
if N<=1 :
  print("not prime")
else:
    for i in range(2,N):
      if N % i == 0:
        print("not a prime")
        break
    else:
      print("is prime")

#4

text = input("Enter a sentance :")

for word in text.split():

    if len(word) % 2 == 0:
        print(word)

#5
def pattern():
    print(1)
    print(2, 2)
    print(3, 3, 3)

pattern()

#6
def palindrome():
    w = input("")

    if w == w[::-1]:
        print("Palindrome")
    else:
        print("Not Palindrome")

palindrome()

#7
def reverse():
  w = input("")
  print(w[::-1])
reverse()

#8
def sum_list():
    numbers = [2, 3, 4, 5, 6]
    print(sum(numbers))

sum_list()

#9
class operations:

    def __init__(self, a):
        self.a = a

    def addition(self, b):
        print(self.a + b)

    def subtraction(self, b):
        print(self.a - b)

    def multiplication(self, b):
        print(self.a * b)

    def division(self, b):
        print(self.a / b)


obj = operations(10)

obj.addition(5)
obj.subtraction(4)
obj.multiplication(3)
obj.division(5)

#10
def even_odd():
    numbers = [3, 2, 9, 5, 4, 6]
    even = []
    odd = []

    for n in numbers:
        if n % 2 == 0:
            even.append(n)
        else:
            odd.append(n)

    print("Even:", even)
    print("Odd:", odd)

even_odd()

#11
def maximum_marks():
    marks = {
        "math": 80,
        "english": 75,
        "science": 90,
        "computer": 95
    }

    highest = 0
    subject = ""

    for k in marks:
        if marks[k] > highest:
            highest = marks[k]
            subject = k

    print(subject)

maximum_marks()

#12
def duplicate():
    numbers = [1, 2, 3, 4, 6, 8, 7, 11, 6]

    for n in range(len(numbers)):
        for k in range(n + 1, len(numbers)):
            if numbers[n] == numbers[k]:
                print(True)
                return

    print(False)

duplicate()

#13
def anagram():
    a = input("Enter first string: ")
    b = input("Enter second string: ")

    if sorted(a) == sorted(b):
        print("Anagram")
    else:
        print("Not Anagram")

anagram()

#14
def maxProfit():
    prices = [7, 1, 5, 3, 6, 4, 5]
    days = [1, 2, 3, 4, 5, 6, 7]

    max_profit = 0
    n = len(prices)
    for i in range(n):
        for j in range(i + 1, n):
            if prices[j] - prices[i] > max_profit:
                max_profit = prices[j] - prices[i]
                buy_day = days[i]
                sell_day = days[j]

    print("Buy on day:", buy_day)
    print("Sell on day:", sell_day)
    print("Maximum profit:", max_profit)

maxProfit()

#15
def sequence():
    nums = [100, 4, 200, 1, 3, 2]
    nums.sort()

    seq = []
    longest = []

    for i in range(len(nums)):
        if i == 0 or nums[i] == nums[i - 1] + 1:
            seq.append(nums[i])
        else:
            if len(seq) > len(longest):
                longest = seq
            seq = [nums[i]]

    if len(seq) > len(longest):
        longest = seq

    print(longest)
    print(len(longest))

sequence()